### ISSUE TITLE
Can't move map and map doesn't bin event

### ISSUE THREAD

**Issue by ggafiled** [MetamediaTechnology/longdo-map-vue#16]
![image](https://user-images.githubusercontent.com/35791150/131820413-acb4faeb-d79a-4ca6-a90f-e2a30b2889bc.png)

Vue 2.9
```
<longdo-map @load="loadMap">

loadMap(map) {
            map.Layers.setBase(longdo.Layers.NORMAL);
            console.log("--- INITIAL LOAD MAP ---");
            console.log(map);
            map.Ui.Mouse.enableDrag(true);
            map.Ui.Keyboard.enableInertia(true); // เปิด-ปิดการการไถลเมื่อเลื่อนแผนที่ด้วย Keyboard
            map.Ui.Keyboard.enable(true); // เปิด-ปิดการใช้งาน Keyboard
            map.Event.bind("doubleClick", function() {
                var result = map.bound();
                console.log(result);
            });
        },
```

**Comment by S-Suraphat** [comment]
@ggafiled ลองใช้เป็น `window.longdo.Layers.NORMAL` แทน `longdo.Layers.NORMAL` ได้มั้ยครับ

**Comment by S-Suraphat** [comment]
เชิญชวนคุณ @ggafiled สามารถมาเข้าร่วมกลุ่ม Longdo Map API Community ได้ที่นี่ [https://www.facebook.com/groups/708165893234850](https://www.facebook.com/groups/708165893234850) นะครับ เผื่อมีข้อสงสัยหรือปัญหาในการใช้งานจะได้สอบถามและเป็นการแบ่งปันให้ท่านอื่นๆ ได้ทราบ เรียนรู้ไปพร้อมๆ กันครับ

**Comment by khopha** [comment]
ขอปิดนะครับ ถ้ายังเจอปัญหาหรือมีข้อมูลเพิ่มเติมรบกวน new issue ใหม่ได้เลยครับ
